### ISSUE TITLE
S3 storage tips

### ISSUE THREAD

**Issue by thomasorten** [tapglue/snaas#50]
Wondering if you have any tips on a good way of making automated ACLs for S3?
I've looked at the ios example app, but would there be a way to restrict access to an apps resources without having to create the credentials manually and without cognito?

**Comment by xla** [comment]
Hej @thomasorten, I'd need more info to answer this question properly. You talking about automatic S3 bucket creation on app creation? And the resources are what exactly?

**Comment by thomasorten** [comment]
Yep. programatically. Images, but with restricted access to only that app.

**Comment by xla** [comment]
Very approrpiate use-case, could you describe the steps of how to secure an S3 bucket per app in a non-automated fashion, then we can explore how it would be done app creation.

**Comment by thomasorten** [comment]
Well I guess I'd have to create a user in IAM, get an access key and secret, create the bucket and attach the user with read/write to that bucket.. Add this to the response on app creation, but also regenerate the key and secret on login/out?

**Comment by xla** [comment]
That sounds like a lot of bookkeeping. Might be better of if you could get signed urls for the assets in the bucket from the backend. The images should only be retrievable by logged-in users of that app, or is there a more complex access model required?

**Comment by thomasorten** [comment]
Yeah true. No, not really. I guess this would be a good starting point? https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-presigned-urls.html

**Comment by xla** [comment]
@thomasorten Yes exactly, I would challenge if you need this level of security, highly depends on the content of the assets/images.

**Comment by xla** [comment]
Please re-open if you see ways how to extend the SNAAS API and or have more questions.
